workflows:
  react-native-fix:
    name: React Native Fix
    environment:
      vars:
        REACT_NATIVE_VERSION: "0.73.0"  # Veya senin versiyonun
    scripts:
      - name: Install specific React Native
        script: |
          cd NetworkAnalyzerAuto
          npm install react-native@0.73.0 --save
          npm install
      
      - name: Build with correct version
        script: |
          cd NetworkAnalyzerAuto/android
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - "**/*.apk"
