workflows:
  try-rn-versions:
    scripts:
      - name: Try multiple RN versions
        script: |
          cd NetworkAnalyzerAuto
          # Önce 0.72 dene
          npm install react-native@0.72.10 --save && npm install && cd android && ./gradlew assembleDebug && exit 0
          # Olmazsa 0.71 dene  
          cd .. && npm install react-native@0.71.0 --save && npm install && cd android && ./gradlew assembleDebug && exit 0
          # Olmazsa 0.70 dene
          cd .. && npm install react-native@0.70.0 --save && npm install && cd android && ./gradlew assembleDebug && exit 0
          echo "All versions failed"
    artifacts:
      - "**/*.apk"
