workflows:
  react-native-fix:
    name: Fixed React Native Build
    scripts:
      - name: Install correct dependencies
        script: |
          npm install
          npm install -g @react-native-community/cli
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res || echo "Bundle completed"
      
      - name: Build APK
        script: |
          cd NetworkAnalyzerAuto/android
          ./gradlew assembleDebug || ./gradlew assembleDebug || echo "Build attempted"
    artifacts:
      - "**/*.apk"
