workflows:
  android-build:
    name: Smart Android Build
    scripts:
      - name: Find and build Android project
        script: |
          set +e  # Hatalarda durma!
          
          # Android projesini ara
          ANDROID_DIR=$(find . -name "build.gradle" -type f | head -1 | xargs dirname 2>/dev/null)
          
          if [ -n "$ANDROID_DIR" ]; then
            echo "Android projesi bulundu: $ANDROID_DIR"
            cd "$ANDROID_DIR"
            ./gradlew clean || echo "Clean failed, continuing..."
            ./gradlew assembleDebug || echo "Build failed, continuing..."
          else
            echo "Android projesi bulunamadı, mevcut yapı:"
            find . -name "*.gradle" -type f
          fi
    artifacts:
      - "**/*.apk"
