workflows:
  brute-force:
    scripts:
      - name: Try Everything for APK
        script: |
          # Tüm olası yolları dene
          (cd NetworkAnalyzerAuto/android && ./gradlew assembleDebug) >/dev/null 2>&1 || true
          (cd android && ./gradlew assembleDebug) >/dev/null 2>&1 || true
          (./gradlew assembleDebug) >/dev/null 2>&1 || true
          (gradle assembleDebug) >/dev/null 2>&1 || true
          echo "All build attempts completed"
    artifacts:
      - "**/*.apk"
