workflows:
  direct-build:
    name: Direct APK Build
    environment:
      groups:
        - android_sdk # Android SDK varsa
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      
      - name: Build with direct Gradle
        script: |
          cd NetworkAnalyzerAuto/android
          gradle assembleDebug
    artifacts:
      - NetworkAnalyzerAuto/android/app/build/outputs/**/*.apk
