workflows:
  android-build:
    name: Direct Android Build
    scripts:
      - name: Debug project structure
        script: |
          echo "=== MEVCUT DİZİN YAPISI ==="
          pwd
          ls -la
          echo "=== ANDROID PROJE ARAMA ==="
          find . -name "build.gradle" -type f
          find . -name "android" -type d
      
      - name: Build APK
        script: |
          # Direkt doğru yolu ver
          cd /Users/codemagic/clone/NetworkAnalyzerAuto/android
          ./gradlew assembleDebug
    artifacts:
      - "NetworkAnalyzerAuto/android/app/build/outputs/**/*.apk"
