workflows:
  final-fix:
    name: Final React Native Fix
    scripts:
      - name: Fix React Native Dependencies
        script: |
          cd NetworkAnalyzerAuto
          # Eksik CLI'ı ekle
          npm install @react-native-community/cli --save-dev --legacy-peer-deps
          # React Native 0.72.10'a downgrade et (stable versiyon)
          npm install react-native@0.72.10 --save --legacy-peer-deps
          npm install --legacy-peer-deps

      - name: Fix Android Gradle Plugin
        script: |
          cd NetworkAnalyzerAuto/android
          # build.gradle'daki plugin versiyonunu düzelt
          sed -i '' 's/com.facebook.react:react-native-gradle-plugin/com.facebook.react:react-native-gradle-plugin:0.72.10/' build.gradle
          # Maven repository ekle
          sed -i '' '/mavenCentral()/a\
          maven { url("$rootDir/../node_modules/react-native/android") }' build.gradle

      - name: Build APK
        script: |
          cd NetworkAnalyzerAuto/android
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - "**/*.apk"
