workflows:
  force-build:
    name: Force Build with Legacy Peers
    scripts:
      - name: Install with force
        script: |
          cd NetworkAnalyzerAuto
          # Tüm dependency conflict'leri ignore et
          npm install --legacy-peer-deps --force
          npm install react-native@0.72.10 --save --legacy-peer-deps
          
      - name: Build with specific plugin
        script: |
          cd NetworkAnalyzerAuto/android
          # build.gradle'da plugin versionunu sabitle
          sed -i '' 's/com.facebook.react:react-native-gradle-plugin/com.facebook.react:react-native-gradle-plugin:0.72.10/' build.gradle
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - "**/*.apk"
