workflows:
  fix-react-native:
    name: Fix React Native Build
    scripts:
      - name: Add missing React Native maven repo
        script: |
          cd NetworkAnalyzerAuto/android
          # build.gradle'a maven repo ekle
          sed -i '' '/mavenCentral()/a\
          maven { url("$rootDir/../node_modules/react-native/android") }' build.gradle
          
      - name: Build APK
        script: |
          cd NetworkAnalyzerAuto/android
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - "**/*.apk"
